import Link from 'next/link'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul className='flex gap-2 mb-4'>
            {['', 'about', 'news', 'contact'].map((page) => (
              <li key={page}>
                <Link className='underline' href={`/${page}`}>
                  {page ? page.slice(0, 1).toUpperCase() + page.slice(1) : 'Top'}
                </Link>
              </li>
            ))}
          </ul>
        </nav>
        {children}</body>
    </html>
  )
}
